name = "MATH50003NumericalAnalysis"
uuid = "5386fd04-56dd-4f23-a623-529daa2d20c5"
version = "0.1.0"
authors = ["Sheehan Olver <solver@mac.com>"]

[deps]
ColorBitstring = "ce91de38-7578-4b98-aebb-6a5df05791d6"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SetRounding = "3cc68bcd-71a2-5612-b932-767ffbe40ab0"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
ColorBitstring = "0.2.0"
IJulia = "1.33.0"
Literate = "2.21.0"
Plots = "1.41.4"
SetRounding = "0.2.1"
Weave = "0.10.12"
